defaults: &DEFAULTS
  host_name: "localhost:3000"
  api_username: test@example.com
  api_pass: password
  api_key: 12345
  description: "description"
  question_prefix: "question_id_"
  descriptive_question_prefix: "descriptive_question_id_"
  investigation_prefix: "investigation_id_"
  uhid_prefix: "NBNC"
  sequence: "SEQ"
  gs_username: "admin@genauth.com"
  gs_password: "htuaneg123"
  gs_spreadsheet_key: "0AsQY57nAWrTldHg2OEtEbjRDcDRsZTZscnhXRHRGanc" 
development:
  <<: *DEFAULTS
test:
  <<: *DEFAULTS
cucumber:
  <<: *DEFAULTS
staging:
  host_name: "my-staging-staging.heroku.com"
  api_username: test@example.com
  api_pass: password
  api_key: 12345
  s3:
    bucket: bucket-name
    access_key_id: secret_key_id
    secret_access_key: secret_key
production:
  host_name: "my-production.heroku.com"
  api_username: test@example.com
  api_pass: password
  api_key: 12345
  s3:
    bucket: bucket-name
    access_key_id: secret_key_id
    secret_access_key: secret_key